name: STM Project Compilation

on:
  push:
    branches:
      - master
      - '**/*develop*'
  pull_request:
    branches: 
      - master
      - '**/*develop*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install ARM toolchain
      run: sudo apt-get install gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi

    - name: Build Project
      shell: bash
      working-directory: ./Build
      run: make -j2


