name: C/C++ CI

on:
  push:
    branches:
      - master
      - '**/*develop*'
  pull_request:
    branches: 
      - master
      - '**/*develop*'
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install ARM toolchain
      run: sudo apt-get install gcc-arm-none-eabi binutils-arm-none-eabi 

    - name: Configure tests/fetch
      shell: bash
      working-directory: ${{runner.workspace}}/Build
      run: make -j4


