# Action from: https://github.com/marketplace/actions/clang-format-check
# Placed in repository by Felipe Telles (felipe.melo.telles@gmail.com)

name: clang-format

# Controls when the workflow will run
on:
  push:
    branches:
      - master
      - '**/*develop*'
  pull_request:
    branches:
      - master
      - '**/*develop*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  formatting-check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.10.2
      with:
        clang-format-version: '16'
        check-path: 'Core'
        # In the following line all files exceptions should be defined
        exclude-regex: '(freertos|main.c|main.h|stm32h7xx|syscalls.c|sysmem.c|FreeRTOSConfig.h)'
