name: clang-format Check

# Controls when the workflow will run
on:
  push:
    branches:
      - master
      - '**/*develop*'
  pull_request:
    branches:
      - master
      - '**/*develop*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.10.2
      with:
        clang-format-version: '13'
        check-path: 'Core'
        exclude-regex: '(freertos|main.c|main.h|stm32h7xx|syscalls.c|sysmem.c|FreeRTOSConfig.h)'