# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DevSkim

on:
  push:
  pull_request:
  schedule:
    - cron: '28 9 * * 3'

jobs:
  lint:
    name: DevSkim
    
    strategy:
      fail-fast: false
    
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1
        with:
          # The sub directory of the repository root to scan. Repository root used by default.
          # Optionally scan the contents of archives.
          should-scan-archives: true
          # The filename for the output.
          output-filename: devskim-results.sarif
        
      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: devskim-results.sarif
